export default {
  APP_INITIALIZED_SUCCESS: 'APP_INITIALIZED_SUCCESS',
  GOOGLE_MAPS_INITIALIZED: 'GOOGLE_MAPS_INITIALIZED',
  FETCH_ZILLOW_DATA_START: 'FETCH_ZILLOW_DATA_START',
  FETCH_ZILLOW_DATA_SUCCESS: 'FETCH_ZILLOW_DATA_SUCCESS',
  FETCH_ZILLOW_DATA_FAILURE: 'FETCH_ZILLOW_DATA_FAILURE',
};
